version: '3'

services:
  db:
    container_name: postgres
    build: ./db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

# データの永続化
volumes:
  postgres:
